spring.application.name=mycoolapp

#Changing the default /actuator base path to something more meaningful for monitoring purposes
management.endpoints.web.base-path=/monitor

#Setting default access to actuator endpoints to be closed, to enhance security. (Not related to spring security)
management.endpoints.access.default=none

# Letting some endpoints to not be affected by the default access settings (not necessarily open-accessed,
# just leaving them have their default behaviour cause we want to explicitly define accessibility for each of them.)
management.endpoint.health.access=unrestricted
management.endpoint.info.access=unrestricted
management.endpoint.beans.access=unrestricted
management.endpoint.threaddump.access=unrestricted
management.endpoint.mappings.access=unrestricted

#Making these endpoints exposed.
management.endpoints.web.exposure.include=health,info,beans,threaddump,mappings
#management.endpoints.web.exposure.include=*

# Leaving this info.env property enabled so that we can define some custom info as json for the application.
management.info.env.enabled=true
# Our custom Json info I provided.
info.application-information.name=@project.name@
info.application-information.description=@project.description@
info.application-information.encoding=@project.build.sourceEncoding@
info.application-information.java.source=@java.version@
info.application-information.java.target=@java.version@


#Defining custom properties to test properties injection
coach.name=Jose Mourinho
team.name=Manchester United

#Changing embedded spring boot properties
server.port=8085
server.servlet.context-path=/delochidemoapp