spring.application.name=mycoolapp
management.endpoints.web.base-path=/monitor
management.endpoints.access.default=none
management.endpoint.health.access=unrestricted
management.endpoint.info.access=unrestricted
management.endpoint.beans.access=unrestricted
management.endpoint.threaddump.access=unrestricted
management.endpoint.mappings.access=unrestricted
management.endpoints.web.exposure.include=health,info,beans,threaddump,mappings
#management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.application-information.name=@project.name@
info.application-information.description=@project.description@
info.application-information.encoding=@project.build.sourceEncoding@
info.application-information.java.source=@java.version@
info.application-information.java.target=@java.version@